version: '3'

services:
  redis:
    container_name: ${CONTAINER_NAME:-redis}
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT:-6379}:6379
    networks:
      - redis
    volumes:
      - ./redis/data:/bitnami/redis/data

networks:
  redis:
    external: true
